# Netlify build configuration
[build]
  # This tells Netlify which folder contains your website files.
  # Since your index.html is in the root of your project, we use "/".
  publish = "/"

# This is a redirect rule for Single-Page Applications like yours.
# It makes sure that if someone refreshes a page like /properties,
# Netlify still loads your main index.html so your React app can handle the routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
